channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pytest
  - pytest-cov
  - coveralls
  - openmdao=3.4.0
  - jsonschema
  - ruamel_yaml
  - pyyaml
  - make
  - xlrd
  - openpyxl
  - cython
  - pandas
  - numpydoc
  - six
  - setuptools
  - git
  - numpy
  - scipy
  - matplotlib
  - geopy
  - pyside2
  - m2w64-toolchain # [win]
  - libpython # [win]
  - compilers # [not win]
  - petsc4py # [not win]
  - mpi4py # [not win]
  - pip:
    - simpy
    - marmot-agents
