channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pytest
  - pytest-cov
  - coveralls
  - openmdao=3.4.0
  - jsonschema
  - ruamel_yaml
  - pyyaml
  - make
  - xlrd
  - openpyxl
  - cython
  - pandas
  - numpydoc
  - six
  - setuptools
  - git
  - numpy
  - scipy
  - matplotlib
  - geopy
  - pyside2
  - m2w64-toolchain
  - libpython
  - compilers
  - petsc4py
  - mpi4py
  - pip
    - simpy
    - marmot-agents
