general:
    verbosity: False

yaml:
    validate: False
    path2schema: wisdem/wisdem/assemblies/reference_turbines/IEAontology_schema.yaml

xfoil:
    path       : /Users/pbortolo/work/1_wisdem/Xfoil/bin/xfoil

openfast:
    run_openfast: True
    Analysis_Level: 1
    FAST_ver: OpenFAST
    dev_branch: True
    FAST_exe: /Users/pbortolo/work/2_openfast/openfast/build/glue-codes/openfast/openfast
    FAST_directory: /Users/pbortolo/work/2_openfast/BAR/OpenFAST_Models/RotorSE_FAST_BAR_2010n_noRe_0_70_to_0_95
    FAST_InputFile: RotorSE_FAST_BAR_2010n_noRe.fst
    path2dll: /Users/pbortolo/work/2_openfast/ROSCO_w_flaps/build/libdiscon.dylib
    Turbsim_exe: "/Users/pbortolo/work/2_openfast/TurbSim/bin/TurbSim_glin64"
    FAST_namingOut: WISDEM_NREL5MW
    FAST_runDirectory: temp/ + wt_initial.FAST_namingOut
    cores: 1
    debug_level: 2
    
rosco:
    n_pitch_perf_surfaces: 20
    min_pitch_perf_surfaces: -5.
    max_pitch_perf_surfaces: 30.
    n_tsr_perf_surfaces: 20
    min_tsr_perf_surfaces: 2.
    max_tsr_perf_surfaces: 12.
    LoggingLevel: 1 # {0: write no debug files, 1: write standard output .dbg-file, 2: write standard output .dbg-file and complete avrSWAP-array .dbg2-file
    F_LPFType: 1 # {1: first-order low-pass filter, 2: second-order low-pass filter}, [rad/s] (currently filters generator speed and pitch control signals)
    F_NotchType: 0 # Notch filter on generator speed and/or tower fore-aft motion (for floating) {0: disable, 1: generator speed, 2: tower-top fore-aft motion, 3: generator speed and tower-top fore-aft motion}
    IPC_ControlMode: 0 # Turn Individual Pitch Control (IPC) for fatigue load reductions (pitch contribution) {0: off, 1: 1P reductions, 2: 1P+2P reductions}
    VS_ControlMode: 2 # Generator torque control mode in above rated conditions {0: constant torque, 1: constant power, 2: TSR tracking PI control}
    PC_ControlMode: 1 # Blade pitch control mode {0: No pitch, fix to fine pitch, 1: active PI blade pitch control}
    Y_ControlMode: 0 # Yaw control mode {0: no yaw control, 1: yaw rate control, 2: yaw-by-IPC}
    SS_Mode: 1 # Setpoint Smoother mode {0: no setpoint smoothing, 1: introduce setpoint smoothing}
    WE_Mode: 2 # Wind speed estimator mode {0: One-second low pass filtered hub height wind speed, 1: Immersion and Invariance Estimator (Ortega et al.)}
    PS_Mode: 1 # Pitch saturation mode {0: no pitch saturation, 1: peak shaving, 2: Cp-maximizing pitch saturation, 3: peak shaving and Cp-maximizing pitch saturation}
    SD_Mode: 0 # Shutdown mode {0: no shutdown procedure, 1: pitch to max pitch at shutdown}
    Fl_Mode: 1 # Floating specific feedback mode {0: no nacelle velocity feedback, 1: nacelle velocity feedback}