general:
    folder_output: outputs
    fname_output: tower_output
design_variables:

  tower:
    outer_diameter:
      flag: True
      lower_bound: 3.87
      upper_bound: 8.0
    layer_thickness:
      flag: True
      lower_bound: 4e-3
      upper_bound: 2e-1

merit_figure: tower_mass

constraints:
  tower:
    height_constraint:
      flag: False
      lower_bound: 1.e-2
      upper_bound: 1.e-2
    stress:
      flag: True
    global_buckling:
      flag: True
    shell_buckling:
      flag: True
    d_to_t:
      flag: True
      lower_bound: 120.0
      upper_bound: 500.0
    taper:
      flag: True
      lower_bound: 0.2
    slope:
      flag: True
    frequency_1:
      flag: True
      lower_bound: 0.13
      upper_bound: 0.40

driver:
    tol: 1.e-6            # Optimality tolerance
    max_iter: 100         # Maximum number of iterations (SLSQP)
    solver: SLSQP         # Optimization solver. Other options are 'SLSQP' - 'CONMIN'
    step_size: 1.e-6      # Step size for finite differencing
    form: forward         # Finite differencing mode, either forward or central

recorder:
    flag: False              # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
