name: Python Package using Conda

on: [push, pull_request]

jobs:
  build:
    name: Compile and run examples
    # We run the script on a matrix of operating systems and python versions
    runs-on: ${{ matrix.os }}
    strategy:
      # Fail-fast set to false lets the jobs across platforms continue even if one fails
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        # $CONDA is an environment variable pointing to the root of the miniconda directory
      
    - name: Add dependendencies ubuntu specific
      if: contains( matrix.os, 'ubuntu')
      run: |
        $CONDA/bin/conda config --add channels conda-forge
        $CONDA/bin/conda install -q pytest pytest-cov coveralls pip openmdao=3.4.0 jsonschema ruamel_yaml pyyaml make xlrd openpyxl cython pandas numpydoc six setuptools git numpy scipy matplotlib geopy pyside2 compilers petsc4py mpi4py 
        $CONDA/bin/pip install simpy marmot-agents
      
    - name: Add dependendencies windows specific
      if: contains( matrix.os, 'windows')
      run: |
        C:\Miniconda\condabin\conda.bat init powershell
        C:\Miniconda\condabin\conda.bat config --add channels conda-forge
        C:\Miniconda\condabin\conda.bat install -q pytest pytest-cov coveralls pip openmdao=3.4.0 jsonschema ruamel_yaml pyyaml make xlrd openpyxl cython pandas numpydoc six setuptools git numpy scipy matplotlib geopy pyside2 m2w64-toolchain libpython
        C:\Miniconda\condabin\pip.bat install simpy marmot-agents

    #- name: Setup tmate session
    #  # Debugging session
    #  uses: mxschmitt/action-tmate@v3
        
    - name: Install WISDEM ubuntu
      if: contains( matrix.os, 'ubuntu')
      run: |
        $CONDA/bin/python setup.py develop
        
    - name: Test with pytest ubuntu
      if: contains( matrix.os, 'ubuntu')
      run: |
        $CONDA/bin/pytest --cov-config=.coverageac --cov=wisdem
        
    - name: Install WISDEM windows
      if: contains( matrix.os, 'windows')
      run: |
        C:\Miniconda\condabin\python.bat setup.py develop
        
    - name: Test with pytest windows
      if: contains( matrix.os, 'windows')
      run: |
        C:\Miniconda\condabin\pytest.bat .
        
    #- name: Set coverage
    #  if: contains( matrix.os, 'ubuntu')
    #  run: |
    #    # Run coveralls
    #    $CONDA/bin/coveralls
    
    #- name: Lint with flake8
    #  run: |
    #    $CONDA/bin/conda install flake8
    #    # stop the build if there are Python syntax errors or undefined names
    #    $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

